version: '3'

services:
  db:
    image: postgres
    env_file:
      - covid_api/.env
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-postgres.sh", "bash", "./entrypoint.sh"]
    env_file:
      - covid_api/.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db