# Generated by Django 3.0.7 on 2020-12-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id_evento_caso', models.IntegerField(primary_key=True, serialize=False)),
                ('sexo', models.TextField(null=True)),
                ('edad', models.FloatField(null=True)),
                ('edad_años_meses', models.TextField(null=True)),
                ('residencia_pais_nombre', models.TextField(null=True)),
                ('residencia_provincia_nombre', models.TextField(null=True)),
                ('residencia_departamento_nombre', models.TextField(null=True)),
                ('carga_provincia_nombre', models.TextField(null=True)),
                ('fecha_inicio_sintomas', models.TextField(null=True)),
                ('fecha_apertura', models.TextField(null=True)),
                ('sepi_apertura', models.IntegerField(null=True)),
                ('fecha_internacion', models.TextField(null=True)),
                ('cuidado_intensivo', models.TextField(null=True)),
                ('fecha_cui_intensivo', models.TextField(null=True)),
                ('fallecido', models.TextField(null=True)),
                ('fecha_fallecimiento', models.TextField(null=True)),
                ('asistencia_respiratoria_mecanica', models.TextField(null=True)),
                ('carga_provincia_id', models.IntegerField(null=True)),
                ('origen_financiamiento', models.TextField(null=True)),
                ('clasificacion', models.TextField(null=True)),
                ('clasificacion_resumen', models.TextField(null=True)),
                ('residencia_provincia_id', models.IntegerField(null=True)),
                ('fecha_diagnostico', models.TextField(null=True)),
                ('residencia_departamento_id', models.IntegerField(null=True)),
                ('ultima_actualizacion', models.TextField(null=True)),
            ],
        ),
    ]
